export default [
  {
    id: 1,
    name: 'Bani',
    gender: 1,
    parent_id: null,
    assets: [],
  },
  {
    id: 2,
    name: 'Budi',
    gender: 1,
    parent_id: 1,
    assets: ['Samsung Universe 9', 'Samsung Galaxy Book'],
  },
  {
    id: 3,
    name: 'Hari',
    gender: 1,
    parent_id: 2,
    assets: ['iPhone 9'],
  },
  {
    id: 4,
    name: 'Siti',
    gender: 2,
    parent_id: 2,
    assets: ['iPhone X'],
  },
  {
    id: 5,
    name: 'Nida',
    gender: 2,
    parent_id: 1,
    assets: ['Huawei P30'],
  },
  {
    id: 6,
    name: 'Bila',
    gender: 2,
    parent_id: 5,
    assets: ['Samsung Universe 9'],
  },
  {
    id: 7,
    name: 'Lesti',
    gender: 2,
    parent_id: 5,
    assets: ['Huawei P30', 'iPhone X'],
  },
  {
    id: 8,
    name: 'Andi',
    gender: 1,
    parent_id: 1,
    assets: ['Samsung Universe 9'],
  },
  {
    id: 9,
    name: 'Diki',
    gender: 1,
    parent_id: 8,
    assets: ['Samsung Galaxy Book'],
  },
  {
    id: 10,
    name: 'Sigit',
    gender: 1,
    parent_id: 1,
    assets: ['Huawei P30'],
  },
  {
    id: 11,
    name: 'Doni',
    gender: 1,
    parent_id: 10,
    assets: ['iPhone X'],
  },
  {
    id: 12,
    name: 'Toni',
    gender: 1,
    parent_id: 10,
    assets: [],
  },
];
